version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/service"
    schedule:
      interval: "weekly"
