services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/db/sql/app:/docker-entrypoint-initdb.d:ro
      - pg-data:/var/lib/postgresql/data
  keycloak-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - ./docker/db/sql/keycloak:/docker-entrypoint-initdb.d:ro
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@db.com
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: always
    ports:
      - "5000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - "db"
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - "keycloak-db"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: start-dev
  service-v2:
    profiles: ["all", "service", "test"]
    build:
      context: .
      target: service-v2-runner
    restart: always
    user: "${UID}"
    ports:
      - "3002:3002"
    depends_on:
      - "db"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      PORT: 3002
      CORS_ORIGIN: http://localhost:5173,http://localhost:3001
    volumes:
      - node-data:/home/node
  web:
    profiles: ["all", "web", "test"]
    build:
      context: .
      target: web-runner
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - "service-v2"
volumes:
  pg-data:
  keycloak-pg-data:
  pgadmin-data:
  node-data:
