/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardGrid: typeof import('./components/CardGrid/CardGrid.vue')['default']
    CardGridButtons: typeof import('./components/CardGrid/CardGridButtons.vue')['default']
    LayoutDefault: typeof import('./components/Layout/LayoutDefault.vue')['default']
    LayoutReports: typeof import('./components/Layout/LayoutReports.vue')['default']
    MeterCard: typeof import('./components/Meter/MeterCard.vue')['default']
    MeterDialog: typeof import('./components/Meter/MeterDialog.vue')['default']
    MeterSelect: typeof import('./components/Meter/MeterSelect.vue')['default']
    MeterTitle: typeof import('./components/Meter/MeterTitle.vue')['default']
    MeterTypeCard: typeof import('./components/MeterType/MeterTypeCard.vue')['default']
    MeterTypeDialog: typeof import('./components/MeterType/MeterTypeDialog.vue')['default']
    MeterTypeSelect: typeof import('./components/MeterType/MeterTypeSelect.vue')['default']
    MeterTypeTitle: typeof import('./components/MeterType/MeterTypeTitle.vue')['default']
    MeterValue: typeof import('./components/Meter/MeterValue.vue')['default']
    NavBar: typeof import('./components/Nav/NavBar.vue')['default']
    NavItem: typeof import('./components/Nav/NavItem.vue')['default']
    NavSnackbarArea: typeof import('./components/Nav/NavSnackbarArea.vue')['default']
    ReportChart: typeof import('./components/Report/ReportChart.vue')['default']
    ReportControls: typeof import('./components/Report/ReportControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnitCard: typeof import('./components/Unit/UnitCard.vue')['default']
    UnitDialog: typeof import('./components/Unit/UnitDialog.vue')['default']
    UnitSelect: typeof import('./components/Unit/UnitSelect.vue')['default']
    UtilDateFormat: typeof import('./components/Util/UtilDateFormat.vue')['default']
    UtilDeleteButton: typeof import('./components/Util/UtilDeleteButton.vue')['default']
    UtilEditOrCreateButton: typeof import('./components/Util/UtilEditOrCreateButton.vue')['default']
    UtilSelect: typeof import('./components/Util/UtilSelect.vue')['default']
    ValueCard: typeof import('./components/Value/ValueCard.vue')['default']
    ValueHistory: typeof import('./components/Value/ValueHistory.vue')['default']
    ValueInput: typeof import('./components/Value/ValueInput.vue')['default']
  }
}
