name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: meter-app

jobs:
  push_to_registry:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: web
          - module: service-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        if: github.event_name != 'release'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        if: github.event_name != 'release'
        run: npm ci
      - name: Run linter
        if: github.event_name != 'release'
        run: npm --workspace=packages/${{matrix.module}} run lint
      - name: Run tests
        if: github.event_name != 'release'
        run: npm --workspace=packages/${{matrix.module}} run test
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-${{ matrix.module }}
      - name: Build and push image to ghcr.io
        uses: docker/build-push-action@v6
        with:
          context: .
          target: ${{ matrix.module }}-runner
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
